name: push

on:
  push:
    branches:
      - main

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Build docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/postmand:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/postmand:latest
